Repository tnamnguyen/mini-capstone, pull requests merged in 2023-03, with the labels that each got.

#58 ArF/admin creation
  client/.env
  client/package-lock.json
  client/package.json
  client/src/Styles/admin.scss
  client/src/components/admin.js
  client/src/components/adminListUsers.js
  client/src/components/createJob.js
  client/src/components/home.js
  client/src/components/jobs.js
  client/src/components/login.js
  client/src/components/navBar.js
  client/src/components/signup.js
  client/src/index.js
  server/server.js
  server/userModel.js
Labels: User Story, Enhancement

#60 Tn/edit profile
  client/src/Styles/editProfile.scss
  client/src/components/editProfile.js
  client/src/components/navBar.js
  client/src/components/profile.js
  server/profileModel.js
  server/server.js
Labels: User Story

#62 Deployment fix
  client/src/components/editProfile.js
  client/src/components/navBar.js
  client/src/components/profile.js
Labels: Bug

#61 Tn/savejobs
  client/.env
  client/src/Styles/job.scss
  client/src/components/createJob.js
  client/src/components/editJob.js
  client/src/components/jobs.js
  client/src/components/login.js
  client/src/components/myJobs.js
  client/src/components/savedJobs.js
  client/src/index.js
  server/server.js
Labels: User Story

#71 Test: Profile
  client/src/components/profile.js
  client/src/tests/profile.test.js
Labels: testing

#91 Minor Fix: Create profile at the moment of account creation
  server/profileModel.js
  server/server.js
Labels: Bug
